# Site
name: '快乐'
description: '做期货的95后'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'personalwebsite'
email: '476541530@qq.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    qing:
      name:           王卿
      site:           https://kuihuaw.github.io
      avatar:         /assets/images/avatar1.jpg
      bio:            "我是一个操盘匠，操盘本领强，我要把内外期市，炒得更漂亮！"
      email:          476541530@qq.com
      weixin:         Levi_wq

    fei:
      name:           王菲
      site:           https://feiwang20.github.io
      avatar:         /assets/images/avatar2.jpg
      bio:            "我是和王卿同志夺食的人。"
      email:          feiwang.w@gmail.com
      weixin:         Silvia--1988

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: qing
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
